# SPDX-FileCopyrightText: 2026 Spiling contributors
# SPDX-License-Identifier: OSL-3.0
# Licensed under the Open Software License version 3.0

[package]
name = "spiling-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
spiling-contracts.workspace = true
serde_json.workspace = true
spiling-geometry.workspace = true
spiling-core.workspace = true
spiling-manufacturing.workspace = true
serde.workspace = true
sha2.workspace = true
parking_lot = "=0.12.5"

[target.'cfg(unix)'.dependencies]
libc = "=0.2.190"

[dev-dependencies]
spiling-engine-client.workspace = true
tokio.workspace = true
