# SPDX-FileCopyrightText: 2026 Spiling contributors
# SPDX-License-Identifier: OSL-3.0
# Licensed under the Open Software License version 3.0

[toolchain]
channel = "1.99.0"
profile = "minimal"
components = ["rustfmt", "clippy"]
