/*!
 * SPDX-FileCopyrightText: 2026 Spiling contributors
 * SPDX-License-Identifier: OSL-3.0
 * Licensed under the Open Software License version 3.0
 */

// Generated by spiling-contracts; do not edit.

export type ArtifactView = { name: string, size_bytes: string, sha256: string, media_type: string, };

export type OperationView = { name: string, done: boolean, state_version: string, state: string, create_time: string | null, update_time: string | null, end_time: string | null, phase: string, completed_units: number, total_units: number, input_revision: string, input_digest: string, outputs: Array<ArtifactView>, error_code: number | null, error_message: string | null, };

export type NativeOperationView = { name: string, session_id: SessionId, captured_scene_revision: SceneRevision, captured_project_revision: ProjectRevision, done: boolean, state_version: string, status: JobStatus, stage: string, completed_units: number, total_units: number, create_time: string | null, update_time: string | null, end_time: string | null, outputs: Array<ArtifactView>, result: JobResult | null, error: JobError | null, };

export type Hello = { instance_id: string, engine_build: string, kernel: string, geometry_capabilities: Array<string>, max_control_bytes: number, max_binary_bytes: number, pid: number, session_id: SessionId, kernel_identity: KernelIdentity, geometry_limits: GeometryLimits, manufacturing_capabilities: Array<string>, project_capabilities: Array<string>, };

export type GeometryErrorCode = "invalid_geometry" | "unsupported_geometry" | "unsupported_units" | "source_io" | "source_changed" | "invalid_pose" | "stale_revision" | "unknown_handle" | "busy" | "resource_limit" | "cancelled" | "degenerate_section" | "kernel_failure";

export type GeometryError = { code: GeometryErrorCode, message: string, };

export type SessionId = string;

export type DefinitionId = string;

export type SourceHash = string;

export type FaceId = string;

export type OccurrenceId = number;

export type ArtifactId = number;

export type SceneRevision = number;

export type AabbMm = { min: [number, number, number], max: [number, number, number], };

export type RigidPoseMm = { translation_mm: [number, number, number], rotation_xyzw: [number, number, number, number], };

export type PlaneMm = { origin_mm: [number, number, number], normal: [number, number, number], };

export type PlaneFrameMm = { origin_mm: [number, number, number], x_axis: [number, number, number], y_axis: [number, number, number], z_axis: [number, number, number], };

export type SourceUnit = "millimetre" | "metre" | "inch";

export type SourceProvenance = { source_hash: SourceHash, source_name: string, source_unit: SourceUnit, 
/**
 * Declared source uncertainty, normalized to mm; not a program-created accuracy guarantee.
 */
uncertainty_mm: number | null, };

export type DisplayProfile = "mesh-mm-0.05-v1";

export type FaceRef = { session_id: SessionId, scene_revision: SceneRevision, occurrence_id: OccurrenceId, definition_id: DefinitionId, face_id: FaceId, };

export type FaceCarrier = { "kind": "plane", origin_mm: [number, number, number], normal: [number, number, number], } | { "kind": "cylinder", axis_origin_mm: [number, number, number], axis_direction: [number, number, number], radius_mm: number, };

export type FaceInfo = { face_id: FaceId, 
/**
 * Decimal string preserves STEP entity IDs above JavaScript's exact integer range.
 */
surface_face_entity: string, source_entity_kind: string, orientation: boolean, carrier: FaceCarrier, };

export type FaceInspection = { reference: FaceRef, face: FaceInfo, pose: RigidPoseMm, provenance: SourceProvenance, };

export type FaceIndexRow = { ordinal: number, face_id: FaceId, };

export type SceneSummary = { session_id: SessionId, revision: SceneRevision, definition_count: number, occurrence_count: number, bounds_mm: AabbMm | null, unique_mesh_bytes: number, };

export type DefinitionRecord = { definition_id: DefinitionId, provenance: SourceProvenance, face_count: number, bounds_mm: AabbMm, mesh_artifact_id: ArtifactId, };

export type OccurrenceRecord = { occurrence_id: OccurrenceId, definition_id: DefinitionId, pose: RigidPoseMm, };

export type NativePath = { "kind": "unix_bytes", hex: string, } | { "kind": "windows_wide", units: Array<number>, };

export type MeshChunkMetadata = { session_id: SessionId, artifact_id: ArtifactId, definition_id: DefinitionId, schema_version: number, mesh_profile: DisplayProfile, chunk_index: number, chunk_count: number, byte_count: number, sha256: SourceHash, face_count: number, bounds_mm: AabbMm, carrier_deviation_mm: number, quantization_error_mm: number, };

export type SectionChunkMetadata = { session_id: SessionId, artifact_id: ArtifactId, schema_version: number, chunk_index: number, chunk_count: number, byte_count: number, sha256: SourceHash, first_loop_ordinal: number, loop_count: number, };

export type SectionLoopMetadata = { ordinal: number, occurrence_id: OccurrenceId, definition_id: DefinitionId, is_hole: boolean, point_count: number, };

export type SectionSummary = { session_id: SessionId, artifact_id: ArtifactId, revision: SceneRevision, schema_version: number, plane: PlaneMm, frame: PlaneFrameMm, total_loop_count: number, chunk_count: number, total_bytes: number, sampling_tolerance_mm: number, boolean_tolerance_mm: number, };

export type GeometryLimits = { source_bytes: number, live_source_bytes: number, step_entities: number, native_faces: number, definitions: number, occurrences: number, display_vertices: number, display_triangles: number, scene_mesh_bytes: number, section_bytes: number, engine_artifact_bytes: number, geometry_chunk_bytes: number, display_buffer_bytes: number, loop_points: number, active_jobs: number, outstanding_chunks: number, };

export type KernelIdentity = { name: string, version: string, revision: string, };

export type SelectedSource = { token: string, session_id: SessionId, label: string, };

export type GeometryCommand = { "op": "import_part", session_id: SessionId, base_revision: SceneRevision, source: NativePath, initial_pose: RigidPoseMm, } | { "op": "add_instance", session_id: SessionId, base_revision: SceneRevision, definition_id: DefinitionId, pose: RigidPoseMm, } | { "op": "set_instance_pose", session_id: SessionId, base_revision: SceneRevision, occurrence_id: OccurrenceId, pose: RigidPoseMm, } | { "op": "remove_instance", session_id: SessionId, base_revision: SceneRevision, occurrence_id: OccurrenceId, } | { "op": "get_scene", session_id: SessionId, } | { "op": "get_scene_page", session_id: SessionId, revision: SceneRevision, kind: ScenePageKind, offset: number, } | { "op": "get_face_index_page", session_id: SessionId, definition_id: DefinitionId, offset: number, } | { "op": "inspect_face", reference: FaceRef, } | { "op": "start_section", session_id: SessionId, base_revision: SceneRevision, plane: PlaneMm, } | { "op": "get_artifact_page", session_id: SessionId, artifact_id: ArtifactId, kind: ArtifactPageKind, offset: number, } | { "op": "release_artifact", session_id: SessionId, artifact_id: ArtifactId, };

export type GeometryResponse = { "type": "operation_accepted", operation: NativeOperationView, } | { "type": "scene_changed", summary: SceneSummary, } | { "type": "scene", summary: SceneSummary, } | { "type": "scene_page", definitions: Array<DefinitionRecord>, occurrences: Array<OccurrenceRecord>, next_offset: number | null, } | { "type": "face_index_page", faces: Array<FaceIndexRow>, next_offset: number | null, } | { "type": "face_inspection", inspection: FaceInspection, } | { "type": "artifact_page", summary: ArtifactSummary, chunks: Array<ArtifactChunkMetadata>, loops: Array<SectionLoopMetadata>, resources: Array<ArtifactView>, next_offset: number | null, } | { "type": "released", } | { "type": "error", error: GeometryError, } | { "type": "project_error", error: ProjectError, };

export type ScenePageKind = "definitions" | "occurrences";

export type ArtifactPageKind = "chunks" | "loops";

export type JobStatus = "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "interrupted";

export type JobResult = { "kind": "scene", summary: SceneSummary, } | { "kind": "section", artifact_id: ArtifactId, } | { "kind": "project_saved", info: ProjectInfo, } | { "kind": "manufacturing_compiled", info: ProjectInfo, record: ManufacturingArtifactRecord, resource: ArtifactView, } | { "kind": "manufacturing_verified", record: ManufacturingArtifactRecord, report: VerificationReport, resource: ArtifactView, };

export type JobError = { "domain": "geometry", error: GeometryError, } | { "domain": "project", error: ProjectError, } | { "domain": "manufacturing", error: ManufacturingError, };

export type ProjectErrorCode = "invalid_project" | "unsupported_format" | "missing_asset" | "corrupt_asset" | "project_locked" | "read_only" | "dirty_project" | "no_saved_path" | "no_undo" | "no_redo" | "stale_revision" | "busy" | "resource_limit" | "cancelled" | "io";

export type ProjectError = { code: ProjectErrorCode, message: string, };

export type ProjectId = string;

export type ProjectRevision = number;

export type ProjectUnits = "mm";

export type ProjectFrame = "right_handed";

export type StoredDefinition = { definition_id: DefinitionId, provenance: SourceProvenance, };

export type ProjectManifest = { format_version: number, project_id: ProjectId, revision: ProjectRevision, units: ProjectUnits, frame: ProjectFrame, next_occurrence: number, definitions: Array<StoredDefinition>, occurrences: Array<OccurrenceRecord>, manufacturing_intent: ManufacturingIntent | null, manufacturing_artifact: ManufacturingArtifactRecord | null, };

export type ProjectInfo = { project_id: ProjectId, revision: ProjectRevision, saved_revision: ProjectRevision | null, path_label: string | null, dirty: boolean, save_uncertain: boolean, read_only: boolean, recovered_previous: boolean, can_undo: boolean, can_redo: boolean, };

export type ProjectCommand = { "op": "get", session_id: SessionId, } | { "op": "new", session_id: SessionId, base_revision: SceneRevision, discard_changes: boolean, } | { "op": "open", session_id: SessionId, base_revision: SceneRevision, path: NativePath, read_only: boolean, recover_previous: boolean, discard_changes: boolean, } | { "op": "save", session_id: SessionId, base_revision: SceneRevision, target: NativePath | null, } | { "op": "undo", session_id: SessionId, base_revision: SceneRevision, } | { "op": "redo", session_id: SessionId, base_revision: SceneRevision, };

export type ProjectResponse = { "type": "status", info: ProjectInfo, } | { "type": "scene_changed", info: ProjectInfo, summary: SceneSummary, } | { "type": "operation_accepted", operation: NativeOperationView, } | { "type": "error", error: ProjectError, };

export type ProjectPathIntent = "open" | "save";

export type SelectedProjectPath = { token: string, session_id: SessionId, label: string, intent: ProjectPathIntent, };

export type ArtifactSummary = { "kind": "mesh", artifact_id: ArtifactId, definition_id: DefinitionId, chunk_count: number, total_bytes: number, } | { "kind": "section", summary: SectionSummary, };

export type ArtifactChunkMetadata = { "kind": "mesh", metadata: MeshChunkMetadata, } | { "kind": "section", metadata: SectionChunkMetadata, };

export type ManufacturingErrorCode = "invalid_specification" | "unsupported_capability" | "unsupported_geometry" | "no_intent" | "empty_project" | "stale_revision" | "verification_failed" | "resource_limit" | "cancelled" | "io" | "corrupt_artifact" | "read_only" | "busy";

export type ManufacturingError = { code: ManufacturingErrorCode, message: string, };

export type PrinterCoordinateFrame = "right_handed_millimetres";

export type MotionSpace = "cartesian_xyz";

export type OutputDialect = "cartesian_absolute_gcode_v1";

export type PrinterCapabilities = { motion_space: MotionSpace, extruders: number, output_dialect: OutputDialect, generated_supports: boolean, };

export type MachineComponentRole = "bed" | "toolhead" | "fixture";

export type MachineComponentShape = { "kind": "box", bounds_mm: AabbMm, } | { "kind": "cylinder", radius_mm: number, height_mm: number, };

export type MachineComponent = { id: string, role: MachineComponentRole, pose: RigidPoseMm, shape: MachineComponentShape, };

export type PrinterSpecification = { schema_version: number, id: string, revision: string, name: string, coordinate_frame: PrinterCoordinateFrame, build_envelope: AabbMm, components: Array<MachineComponent>, capabilities: PrinterCapabilities, nozzle_diameter_mm: number, max_feed_mm_s: number, max_volumetric_flow_mm3_s: number, };

export type PlanarPrintRecipe = { id: string, revision: string, material_id: string, material_revision: string, filament_diameter_mm: number, layer_height_mm: number, bead_width_mm: number, perimeter_count: number, infill_fraction: number, print_speed_mm_s: number, travel_speed_mm_s: number, flow_multiplier: number, };

export type ManufacturingIntent = { printer: PrinterSpecification, recipe: PlanarPrintRecipe, };

export type DepositionKind = "perimeter" | "solid_fill";

export type DepositionPath = { kind: DepositionKind, points_mm: Array<[number, number, number]>, };

export type PrintLayer = { index: number, z_mm: number, section_z_mm: number, paths: Array<DepositionPath>, };

export type NormalizedPrintPlan = { schema_version: number, layers: Array<PrintLayer>, sampling_tolerance_mm: number, offset_tolerance_mm: number, layer_quantization_mm: number, };

export type ManufacturingProvenance = { project_id: ProjectId, input_revision: ProjectRevision, input_hash: SourceHash, definitions: Array<StoredDefinition>, occurrences: Array<OccurrenceRecord>, intent: ManufacturingIntent, kernel: KernelIdentity, planner_version: string, emitter_version: string, verifier_version: string, };

export type VerificationReport = { verified: boolean, coverage: Array<string>, limitations: Array<string>, deposition_segments: number, travel_segments: number, deposited_volume_mm3: number, filament_length_mm: number, max_position_error_mm: number, max_extrusion_error_mm: number, };

export type ManufacturingSummary = { layers: number, paths: number, deposition_segments: number, deposited_volume_mm3: number, filament_length_mm: number, software_only: boolean, };

export type ManufacturingBundle = { schema_version: number, provenance: ManufacturingProvenance, plan: NormalizedPrintPlan, program: string, verification: VerificationReport, };

export type ManufacturingArtifactRecord = { hash: SourceHash, input_hash: SourceHash, byte_count: number, summary: ManufacturingSummary, };

export type ManufacturingCommand = { "op": "get", session_id: SessionId, } | { "op": "set_intent", session_id: SessionId, base_revision: ProjectRevision, intent: ManufacturingIntent, } | { "op": "compile", session_id: SessionId, base_revision: ProjectRevision, } | { "op": "inspect", session_id: SessionId, base_revision: ProjectRevision, };

export type ManufacturingResponse = { "type": "status", info: ProjectInfo, intent: ManufacturingIntent | null, artifact: ManufacturingArtifactRecord | null, resource: ArtifactView | null, } | { "type": "operation_accepted", operation: NativeOperationView, } | { "type": "verified", record: ManufacturingArtifactRecord, report: VerificationReport, resource: ArtifactView, } | { "type": "error", error: ManufacturingError, };

export const MAX_CONTROL_BYTES = 65536 as const;
export const MAX_BINARY_BYTES = 4194304 as const;
export const TRIANGLE_SCHEMA_VERSION = 1 as const;
export const TRIANGLE_HEADER_BYTES = 16 as const;
export const TRIANGLE_VERTEX_COUNT = 3 as const;
export const TRIANGLE_INDEX_COUNT = 3 as const;
export const MESH_SCHEMA_VERSION = 1 as const;
export const MESH_HEADER_BYTES = 64 as const;
export const SECTION_SCHEMA_VERSION = 1 as const;
export const SECTION_HEADER_BYTES = 64 as const;
export const MAX_SOURCE_BYTES = 16777216 as const;
export const MAX_LIVE_SOURCE_BYTES = 67108864 as const;
export const MAX_STEP_ENTITIES = 100000 as const;
export const MAX_NATIVE_FACES = 50000 as const;
export const MAX_DEFINITIONS = 32 as const;
export const MAX_OCCURRENCES = 256 as const;
export const MAX_DISPLAY_VERTICES = 1000000 as const;
export const MAX_DISPLAY_TRIANGLES = 1000000 as const;
export const MAX_SCENE_MESH_BYTES = 67108864 as const;
export const MAX_SECTION_BYTES = 16777216 as const;
export const MAX_ENGINE_ARTIFACT_BYTES = 134217728 as const;
export const MAX_GEOMETRY_CHUNK_BYTES = 1048576 as const;
export const MAX_DISPLAY_BUFFER_BYTES = 134217728 as const;
export const MAX_LOOP_POINTS = 40000 as const;
export const MAX_NATIVE_PATH_UNITS = 8192 as const;
export const MAX_DISPLAY_LABEL_BYTES = 256 as const;
export const MAX_ERROR_MESSAGE_BYTES = 1024 as const;
export const SCENE_PAGE_SIZE = 64 as const;
export const FACE_PAGE_SIZE = 256 as const;
export const ARTIFACT_PAGE_SIZE = 64 as const;
export const MAX_TERMINAL_JOBS = 64 as const;
export const JOB_POLL_INTERVAL_MS = 100 as const;
export const JOB_CANCEL_AFTER_MS = 60000 as const;
export const JOB_CANCEL_GRACE_MS = 10000 as const;
export const MAX_ACTIVE_GEOMETRY_JOBS = 1 as const;
export const MAX_OUTSTANDING_CHUNKS = 1 as const;
export const PROJECT_FORMAT_VERSION = 2 as const;
export const MAX_PROJECT_MANIFEST_BYTES = 1048576 as const;
export const MAX_PROJECT_HISTORY = 64 as const;
export const MAX_PROJECT_STORED_SOURCE_BYTES = 268435456 as const;
export const MAX_PROJECT_STORED_ASSETS = 128 as const;
export const MAX_PROJECT_ERROR_BYTES = 2048 as const;
export const MANUFACTURING_SCHEMA_VERSION = 1 as const;
export const MAX_MANUFACTURING_BUNDLE_BYTES = 16777216 as const;
export const MAX_MANUFACTURING_RETAINED_BYTES = 67108864 as const;
export const MAX_PRINT_LAYERS = 4096 as const;
export const MAX_DEPOSITION_SEGMENTS = 100000 as const;
export const MAX_MACHINE_COMPONENTS = 64 as const;
export const MAX_PROFILE_JSON_BYTES = 32768 as const;
export const MAX_MANUFACTURING_ERROR_BYTES = 2048 as const;
export const MAX_MANUFACTURING_LABEL_BYTES = 256 as const;
export const MESH_CARRIER_TOLERANCE_MM = 0.025 as const;
export const MESH_QUANTIZATION_TOLERANCE_MM = 0.025 as const;
export const MESH_SURFACE_TOLERANCE_MM = 0.05 as const;
export const SECTION_SAMPLING_TOLERANCE_MM = 0.005 as const;
export const SECTION_BOOLEAN_TOLERANCE_MM = 0.00001 as const;
export const SECTION_PLANE_TOLERANCE_MM = 0.0001 as const;
export const POSE_NORM_TOLERANCE = 0.0000000001 as const;
export const NORMAL_NORM_TOLERANCE = 0.0001 as const;
export const IMPORT_PROFILE = "step-planar-cylindrical-v1" as const;
export const MESH_PROFILE = "mesh-mm-0.05-v1" as const;
