/*!
 * SPDX-FileCopyrightText: 2026 Spiling contributors
 * SPDX-License-Identifier: OSL-3.0
 * Licensed under the Open Software License version 3.0
 */

// Generated by spiling-contracts; do not edit.

export type ArtifactView = { name: string, size_bytes: string, sha256: string, media_type: string, };

export type Hello = { instance_id: string, engine_build: string, kernel: string, geometry_capabilities: Array<string>, max_control_bytes: number, max_binary_bytes: number, pid: number, };

export type OperationView = { name: string, done: boolean, state_version: string, state: string, create_time: string | null, update_time: string | null, end_time: string | null, phase: string, completed_units: number, total_units: number, input_revision: string, input_digest: string, outputs: Array<ArtifactView>, error_code: number | null, error_message: string | null, };

export const MAX_CONTROL_BYTES = 65536 as const;
export const MAX_BINARY_BYTES = 4194304 as const;
export const TRIANGLE_SCHEMA_VERSION = 1 as const;
export const TRIANGLE_HEADER_BYTES = 16 as const;
export const TRIANGLE_VERTEX_COUNT = 3 as const;
export const TRIANGLE_INDEX_COUNT = 3 as const;
