/*!
 * SPDX-FileCopyrightText: 2026 Spiling contributors
 * SPDX-License-Identifier: OSL-3.0
 * Licensed under the Open Software License version 3.0
 */

// Generated by spiling-contracts; do not edit.

export type Request = { "type": "hello", protocol_version: number, client_build: string, } | { "type": "ping", } | { "type": "triangle", } | { "type": "shutdown", };

export type Hello = { protocol_version: number, engine_build: string, 
/**
 * Configured future default, not evidence of a linked kernel.
 */
kernel: string, geometry_capabilities: Array<string>, max_control_bytes: number, max_binary_bytes: number, pid: number, };

export type Response = { "type": "hello" } & Hello | { "type": "pong", } | { "type": "bye", } | { "type": "error", code: string, message: string, };

export const PROTOCOL_VERSION = 1 as const;
export const FRAME_HEADER_BYTES = 16 as const;
export const MAX_CONTROL_BYTES = 65536 as const;
export const MAX_BINARY_BYTES = 4194304 as const;
export const TRIANGLE_SCHEMA_VERSION = 1 as const;
export const TRIANGLE_HEADER_BYTES = 16 as const;
export const TRIANGLE_VERTEX_COUNT = 3 as const;
export const TRIANGLE_INDEX_COUNT = 3 as const;
